# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - redisshoppingcart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: redisshoppingcart:latest

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerarpan.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_14d06ac1d9db4f388e026d9aba253d77 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4728889c53284407ae1fd0b0ab827bf3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerarpan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_14d06ac1d9db4f388e026d9aba253d77 }}/redisshoppingcart:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'redisshoppingcart'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_62faeaf92da74466ac83d340f9fd2eae }}
        images: 'testdockerarpan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_14d06ac1d9db4f388e026d9aba253d77 }}/redisshoppingcart:${{ github.sha }}'